// Code generated by go-swagger; DO NOT EDIT.

package hosts_api

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// GetHostInfoOKCode is the HTTP code returned for type GetHostInfoOK
const GetHostInfoOKCode int = 200

/*GetHostInfoOK list the hosts' info

swagger:response getHostInfoOK
*/
type GetHostInfoOK struct {

	/*
	  In: Body
	*/
	Payload *GetHostInfoOKBody `json:"body,omitempty"`
}

// NewGetHostInfoOK creates GetHostInfoOK with default headers values
func NewGetHostInfoOK() *GetHostInfoOK {

	return &GetHostInfoOK{}
}

// WithPayload adds the payload to the get host info o k response
func (o *GetHostInfoOK) WithPayload(payload *GetHostInfoOKBody) *GetHostInfoOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get host info o k response
func (o *GetHostInfoOK) SetPayload(payload *GetHostInfoOKBody) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetHostInfoOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetHostInfoBadRequestCode is the HTTP code returned for type GetHostInfoBadRequest
const GetHostInfoBadRequestCode int = 400

/*GetHostInfoBadRequest bad request

swagger:response getHostInfoBadRequest
*/
type GetHostInfoBadRequest struct {

	/*
	  In: Body
	*/
	Payload *GetHostInfoBadRequestBody `json:"body,omitempty"`
}

// NewGetHostInfoBadRequest creates GetHostInfoBadRequest with default headers values
func NewGetHostInfoBadRequest() *GetHostInfoBadRequest {

	return &GetHostInfoBadRequest{}
}

// WithPayload adds the payload to the get host info bad request response
func (o *GetHostInfoBadRequest) WithPayload(payload *GetHostInfoBadRequestBody) *GetHostInfoBadRequest {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get host info bad request response
func (o *GetHostInfoBadRequest) SetPayload(payload *GetHostInfoBadRequestBody) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetHostInfoBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(400)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetHostInfoUnauthorizedCode is the HTTP code returned for type GetHostInfoUnauthorized
const GetHostInfoUnauthorizedCode int = 401

/*GetHostInfoUnauthorized Unauthorized

swagger:response getHostInfoUnauthorized
*/
type GetHostInfoUnauthorized struct {
}

// NewGetHostInfoUnauthorized creates GetHostInfoUnauthorized with default headers values
func NewGetHostInfoUnauthorized() *GetHostInfoUnauthorized {

	return &GetHostInfoUnauthorized{}
}

// WriteResponse to the client
func (o *GetHostInfoUnauthorized) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(401)
}
