// Code generated by go-swagger; DO NOT EDIT.

package hosts_api

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"context"
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime/middleware"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// QueryOneHostInfoHandlerFunc turns a function with the right signature into a query one host info handler
type QueryOneHostInfoHandlerFunc func(QueryOneHostInfoParams) middleware.Responder

// Handle executing the request and returning a response
func (fn QueryOneHostInfoHandlerFunc) Handle(params QueryOneHostInfoParams) middleware.Responder {
	return fn(params)
}

// QueryOneHostInfoHandler interface for that can handle valid query one host info params
type QueryOneHostInfoHandler interface {
	Handle(QueryOneHostInfoParams) middleware.Responder
}

// NewQueryOneHostInfo creates a new http.Handler for the query one host info operation
func NewQueryOneHostInfo(ctx *middleware.Context, handler QueryOneHostInfoHandler) *QueryOneHostInfo {
	return &QueryOneHostInfo{Context: ctx, Handler: handler}
}

/* QueryOneHostInfo swagger:route GET /hostInfo hosts_api queryOneHostInfo

return one machines info

*/
type QueryOneHostInfo struct {
	Context *middleware.Context
	Handler QueryOneHostInfoHandler
}

func (o *QueryOneHostInfo) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewQueryOneHostInfoParams()
	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}

// QueryOneHostInfoBadRequestBody query one host info bad request body
//
// swagger:model QueryOneHostInfoBadRequestBody
type QueryOneHostInfoBadRequestBody struct {

	// message
	Message string `json:"message,omitempty"`
}

// Validate validates this query one host info bad request body
func (o *QueryOneHostInfoBadRequestBody) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this query one host info bad request body based on context it is used
func (o *QueryOneHostInfoBadRequestBody) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (o *QueryOneHostInfoBadRequestBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *QueryOneHostInfoBadRequestBody) UnmarshalBinary(b []byte) error {
	var res QueryOneHostInfoBadRequestBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}

// QueryOneHostInfoOKBody query one host info o k body
//
// swagger:model QueryOneHostInfoOKBody
type QueryOneHostInfoOKBody struct {

	// current RAM
	CurrentRAM float32 `json:"currentRAM,omitempty"`

	// hostname
	Hostname string `json:"hostname,omitempty"`

	// ip
	// Min Length: 1
	IP string `json:"ip,omitempty"`

	// percent CPU
	PercentCPU float32 `json:"percentCPU,omitempty"`

	// percent RAM
	PercentRAM float32 `json:"percentRAM,omitempty"`

	// port
	Port string `json:"port,omitempty"`

	// total RAM
	TotalRAM float32 `json:"totalRAM,omitempty"`
}

// Validate validates this query one host info o k body
func (o *QueryOneHostInfoOKBody) Validate(formats strfmt.Registry) error {
	var res []error

	if err := o.validateIP(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *QueryOneHostInfoOKBody) validateIP(formats strfmt.Registry) error {
	if swag.IsZero(o.IP) { // not required
		return nil
	}

	if err := validate.MinLength("queryOneHostInfoOK"+"."+"ip", "body", o.IP, 1); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this query one host info o k body based on context it is used
func (o *QueryOneHostInfoOKBody) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (o *QueryOneHostInfoOKBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *QueryOneHostInfoOKBody) UnmarshalBinary(b []byte) error {
	var res QueryOneHostInfoOKBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}
