// Code generated by go-swagger; DO NOT EDIT.

package hosts_api

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// QueryHostInfoOKCode is the HTTP code returned for type QueryHostInfoOK
const QueryHostInfoOKCode int = 200

/*QueryHostInfoOK list the hosts' info

swagger:response queryHostInfoOK
*/
type QueryHostInfoOK struct {

	/*
	  In: Body
	*/
	Payload []*QueryHostInfoOKBodyItems0 `json:"body,omitempty"`
}

// NewQueryHostInfoOK creates QueryHostInfoOK with default headers values
func NewQueryHostInfoOK() *QueryHostInfoOK {

	return &QueryHostInfoOK{}
}

// WithPayload adds the payload to the query host info o k response
func (o *QueryHostInfoOK) WithPayload(payload []*QueryHostInfoOKBodyItems0) *QueryHostInfoOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the query host info o k response
func (o *QueryHostInfoOK) SetPayload(payload []*QueryHostInfoOKBodyItems0) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *QueryHostInfoOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	payload := o.Payload
	if payload == nil {
		// return empty array
		payload = make([]*QueryHostInfoOKBodyItems0, 0, 50)
	}

	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}
}

// QueryHostInfoBadRequestCode is the HTTP code returned for type QueryHostInfoBadRequest
const QueryHostInfoBadRequestCode int = 400

/*QueryHostInfoBadRequest bad request

swagger:response queryHostInfoBadRequest
*/
type QueryHostInfoBadRequest struct {

	/*
	  In: Body
	*/
	Payload *QueryHostInfoBadRequestBody `json:"body,omitempty"`
}

// NewQueryHostInfoBadRequest creates QueryHostInfoBadRequest with default headers values
func NewQueryHostInfoBadRequest() *QueryHostInfoBadRequest {

	return &QueryHostInfoBadRequest{}
}

// WithPayload adds the payload to the query host info bad request response
func (o *QueryHostInfoBadRequest) WithPayload(payload *QueryHostInfoBadRequestBody) *QueryHostInfoBadRequest {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the query host info bad request response
func (o *QueryHostInfoBadRequest) SetPayload(payload *QueryHostInfoBadRequestBody) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *QueryHostInfoBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(400)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// QueryHostInfoUnauthorizedCode is the HTTP code returned for type QueryHostInfoUnauthorized
const QueryHostInfoUnauthorizedCode int = 401

/*QueryHostInfoUnauthorized Unauthorized

swagger:response queryHostInfoUnauthorized
*/
type QueryHostInfoUnauthorized struct {
}

// NewQueryHostInfoUnauthorized creates QueryHostInfoUnauthorized with default headers values
func NewQueryHostInfoUnauthorized() *QueryHostInfoUnauthorized {

	return &QueryHostInfoUnauthorized{}
}

// WriteResponse to the client
func (o *QueryHostInfoUnauthorized) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(401)
}
