// Code generated by go-swagger; DO NOT EDIT.

package hosts_api

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// QueryOneHostInfoOKCode is the HTTP code returned for type QueryOneHostInfoOK
const QueryOneHostInfoOKCode int = 200

/*QueryOneHostInfoOK list the hosts' info

swagger:response queryOneHostInfoOK
*/
type QueryOneHostInfoOK struct {

	/*
	  In: Body
	*/
	Payload *QueryOneHostInfoOKBody `json:"body,omitempty"`
}

// NewQueryOneHostInfoOK creates QueryOneHostInfoOK with default headers values
func NewQueryOneHostInfoOK() *QueryOneHostInfoOK {

	return &QueryOneHostInfoOK{}
}

// WithPayload adds the payload to the query one host info o k response
func (o *QueryOneHostInfoOK) WithPayload(payload *QueryOneHostInfoOKBody) *QueryOneHostInfoOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the query one host info o k response
func (o *QueryOneHostInfoOK) SetPayload(payload *QueryOneHostInfoOKBody) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *QueryOneHostInfoOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// QueryOneHostInfoBadRequestCode is the HTTP code returned for type QueryOneHostInfoBadRequest
const QueryOneHostInfoBadRequestCode int = 400

/*QueryOneHostInfoBadRequest bad request

swagger:response queryOneHostInfoBadRequest
*/
type QueryOneHostInfoBadRequest struct {

	/*
	  In: Body
	*/
	Payload *QueryOneHostInfoBadRequestBody `json:"body,omitempty"`
}

// NewQueryOneHostInfoBadRequest creates QueryOneHostInfoBadRequest with default headers values
func NewQueryOneHostInfoBadRequest() *QueryOneHostInfoBadRequest {

	return &QueryOneHostInfoBadRequest{}
}

// WithPayload adds the payload to the query one host info bad request response
func (o *QueryOneHostInfoBadRequest) WithPayload(payload *QueryOneHostInfoBadRequestBody) *QueryOneHostInfoBadRequest {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the query one host info bad request response
func (o *QueryOneHostInfoBadRequest) SetPayload(payload *QueryOneHostInfoBadRequestBody) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *QueryOneHostInfoBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(400)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// QueryOneHostInfoUnauthorizedCode is the HTTP code returned for type QueryOneHostInfoUnauthorized
const QueryOneHostInfoUnauthorizedCode int = 401

/*QueryOneHostInfoUnauthorized Unauthorized

swagger:response queryOneHostInfoUnauthorized
*/
type QueryOneHostInfoUnauthorized struct {
}

// NewQueryOneHostInfoUnauthorized creates QueryOneHostInfoUnauthorized with default headers values
func NewQueryOneHostInfoUnauthorized() *QueryOneHostInfoUnauthorized {

	return &QueryOneHostInfoUnauthorized{}
}

// WriteResponse to the client
func (o *QueryOneHostInfoUnauthorized) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(401)
}
