version: "3.8"
services:
  database:
    image: "postgres:alpine"
    restart: always
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - server_db:/var/lib/postgresql/data
  backend:
    build: ./tides-server
    volumes:
      - ./tides-server:/data
    env_file:
      - .env
    ports:
      - "8033:8033"
    stdin_open: true
    tty: true
    depends_on:
      - database
    entrypoint: ["/build/backend"]
  webssh:
    build: ./webssh
    ports:
      - "8888:8888"
    depends_on:
      - backend
  frontend:
    build:
      context: ./ui
      args:
        - MOD=dev
    volumes:
      - ./ui:/app
      # One-way volume to use node_modules from inside image
      - /app/node_modules
    ports:
      - "80:80"
    depends_on:
      - backend
#      - webssh

volumes:
  server_db:
