// Code generated by go-swagger; DO NOT EDIT.

package restapi

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
)

var (
	// SwaggerJSON embedded version of the swagger document used at generation time
	SwaggerJSON json.RawMessage
	// FlatSwaggerJSON embedded flattened version of the swagger document used at generation time
	FlatSwaggerJSON json.RawMessage
)

func init() {
	SwaggerJSON = json.RawMessage([]byte(`{
  "consumes": [
    "application/json"
  ],
  "produces": [
    "application/json"
  ],
  "schemes": [
    "http"
  ],
  "swagger": "2.0",
  "info": {
    "title": "Greeting Server",
    "version": "1.0.0"
  },
  "paths": {
    "/addHost": {
      "get": {
        "tags": [
          "hosts"
        ],
        "operationId": "findHosts",
        "parameters": [
          {
            "type": "integer",
            "format": "int64",
            "name": "since",
            "in": "query"
          },
          {
            "type": "integer",
            "format": "int32",
            "default": 20,
            "name": "limit",
            "in": "query"
          }
        ],
        "responses": {
          "200": {
            "description": "list the hosts",
            "schema": {
              "type": "array",
              "items": {
                "type": "object",
                "properties": {
                  "completed": {
                    "type": "boolean"
                  },
                  "id": {
                    "type": "integer",
                    "format": "int64",
                    "readOnly": true
                  },
                  "ip": {
                    "type": "string",
                    "minLength": 1
                  }
                }
              }
            }
          },
          "default": {
            "description": "generic error response",
            "schema": {
              "$ref": "#/definitions/error"
            }
          }
        }
      },
      "post": {
        "tags": [
          "hosts"
        ],
        "operationId": "addOneHost",
        "parameters": [
          {
            "name": "body",
            "in": "body",
            "schema": {
              "type": "object",
              "properties": {
                "completed": {
                  "type": "boolean"
                },
                "id": {
                  "type": "integer",
                  "format": "int64",
                  "readOnly": true
                },
                "ip": {
                  "type": "string",
                  "minLength": 1
                }
              }
            }
          }
        ],
        "responses": {
          "201": {
            "description": "Created",
            "schema": {
              "type": "object",
              "properties": {
                "completed": {
                  "type": "boolean"
                },
                "id": {
                  "type": "integer",
                  "format": "int64",
                  "readOnly": true
                },
                "ip": {
                  "type": "string",
                  "minLength": 1
                }
              }
            }
          },
          "default": {
            "description": "error",
            "schema": {
              "$ref": "#/definitions/error"
            }
          }
        }
      }
    },
    "/hello": {
      "get": {
        "produces": [
          "text/plain"
        ],
        "operationId": "getGreeting",
        "parameters": [
          {
            "type": "string",
            "description": "defaults to World if not given",
            "name": "name",
            "in": "query"
          }
        ],
        "responses": {
          "200": {
            "description": "returns a greeting",
            "schema": {
              "description": "contains the actual greeting as plain text",
              "type": "string"
            }
          }
        }
      }
    },
    "/hostsStatus": {
      "get": {
        "tags": [
          "hosts"
        ],
        "operationId": "queryHostInfo",
        "parameters": [
          {
            "type": "integer",
            "format": "int64",
            "name": "since",
            "in": "query"
          },
          {
            "type": "integer",
            "format": "int32",
            "default": 20,
            "name": "limit",
            "in": "query"
          }
        ],
        "responses": {
          "200": {
            "description": "list the hosts' info",
            "schema": {
              "type": "array",
              "items": {
                "type": "object",
                "properties": {
                  "id": {
                    "type": "integer",
                    "format": "int64",
                    "readOnly": true
                  },
                  "info": {
                    "type": "string"
                  },
                  "ip": {
                    "type": "string",
                    "minLength": 1
                  }
                }
              }
            }
          },
          "default": {
            "description": "generic error response",
            "schema": {
              "$ref": "#/definitions/error"
            }
          }
        }
      }
    }
  },
  "definitions": {
    "error": {
      "type": "object",
      "required": [
        "message"
      ],
      "properties": {
        "code": {
          "type": "integer",
          "format": "int64"
        },
        "message": {
          "type": "string"
        }
      }
    },
    "item": {
      "type": "object",
      "properties": {
        "completed": {
          "type": "boolean"
        },
        "id": {
          "type": "integer",
          "format": "int64",
          "readOnly": true
        },
        "ip": {
          "type": "string",
          "minLength": 1
        }
      }
    }
  }
}`))
	FlatSwaggerJSON = json.RawMessage([]byte(`{
  "consumes": [
    "application/json"
  ],
  "produces": [
    "application/json"
  ],
  "schemes": [
    "http"
  ],
  "swagger": "2.0",
  "info": {
    "title": "Greeting Server",
    "version": "1.0.0"
  },
  "paths": {
    "/addHost": {
      "get": {
        "tags": [
          "hosts"
        ],
        "operationId": "findHosts",
        "parameters": [
          {
            "type": "integer",
            "format": "int64",
            "name": "since",
            "in": "query"
          },
          {
            "type": "integer",
            "format": "int32",
            "default": 20,
            "name": "limit",
            "in": "query"
          }
        ],
        "responses": {
          "200": {
            "description": "list the hosts",
            "schema": {
              "type": "array",
              "items": {
                "$ref": "#/definitions/FindHostsOKBodyItems0"
              }
            }
          },
          "default": {
            "description": "generic error response",
            "schema": {
              "$ref": "#/definitions/error"
            }
          }
        }
      },
      "post": {
        "tags": [
          "hosts"
        ],
        "operationId": "addOneHost",
        "parameters": [
          {
            "name": "body",
            "in": "body",
            "schema": {
              "type": "object",
              "properties": {
                "completed": {
                  "type": "boolean"
                },
                "id": {
                  "type": "integer",
                  "format": "int64",
                  "readOnly": true
                },
                "ip": {
                  "type": "string",
                  "minLength": 1
                }
              }
            }
          }
        ],
        "responses": {
          "201": {
            "description": "Created",
            "schema": {
              "type": "object",
              "properties": {
                "completed": {
                  "type": "boolean"
                },
                "id": {
                  "type": "integer",
                  "format": "int64",
                  "readOnly": true
                },
                "ip": {
                  "type": "string",
                  "minLength": 1
                }
              }
            }
          },
          "default": {
            "description": "error",
            "schema": {
              "$ref": "#/definitions/error"
            }
          }
        }
      }
    },
    "/hello": {
      "get": {
        "produces": [
          "text/plain"
        ],
        "operationId": "getGreeting",
        "parameters": [
          {
            "type": "string",
            "description": "defaults to World if not given",
            "name": "name",
            "in": "query"
          }
        ],
        "responses": {
          "200": {
            "description": "returns a greeting",
            "schema": {
              "description": "contains the actual greeting as plain text",
              "type": "string"
            }
          }
        }
      }
    },
    "/hostsStatus": {
      "get": {
        "tags": [
          "hosts"
        ],
        "operationId": "queryHostInfo",
        "parameters": [
          {
            "type": "integer",
            "format": "int64",
            "name": "since",
            "in": "query"
          },
          {
            "type": "integer",
            "format": "int32",
            "default": 20,
            "name": "limit",
            "in": "query"
          }
        ],
        "responses": {
          "200": {
            "description": "list the hosts' info",
            "schema": {
              "type": "array",
              "items": {
                "$ref": "#/definitions/QueryHostInfoOKBodyItems0"
              }
            }
          },
          "default": {
            "description": "generic error response",
            "schema": {
              "$ref": "#/definitions/error"
            }
          }
        }
      }
    }
  },
  "definitions": {
    "FindHostsOKBodyItems0": {
      "type": "object",
      "properties": {
        "completed": {
          "type": "boolean"
        },
        "id": {
          "type": "integer",
          "format": "int64",
          "readOnly": true
        },
        "ip": {
          "type": "string",
          "minLength": 1
        }
      }
    },
    "QueryHostInfoOKBodyItems0": {
      "type": "object",
      "properties": {
        "id": {
          "type": "integer",
          "format": "int64",
          "readOnly": true
        },
        "info": {
          "type": "string"
        },
        "ip": {
          "type": "string",
          "minLength": 1
        }
      }
    },
    "error": {
      "type": "object",
      "required": [
        "message"
      ],
      "properties": {
        "code": {
          "type": "integer",
          "format": "int64"
        },
        "message": {
          "type": "string"
        }
      }
    },
    "item": {
      "type": "object",
      "properties": {
        "completed": {
          "type": "boolean"
        },
        "id": {
          "type": "integer",
          "format": "int64",
          "readOnly": true
        },
        "ip": {
          "type": "string",
          "minLength": 1
        }
      }
    }
  }
}`))
}
