// Code generated by go-swagger; DO NOT EDIT.

package hosts_api

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// DeleteHostsOKCode is the HTTP code returned for type DeleteHostsOK
const DeleteHostsOKCode int = 200

/*DeleteHostsOK successfully delete the host

swagger:response deleteHostsOK
*/
type DeleteHostsOK struct {

	/*
	  In: Body
	*/
	Payload *DeleteHostsOKBody `json:"body,omitempty"`
}

// NewDeleteHostsOK creates DeleteHostsOK with default headers values
func NewDeleteHostsOK() *DeleteHostsOK {

	return &DeleteHostsOK{}
}

// WithPayload adds the payload to the delete hosts o k response
func (o *DeleteHostsOK) WithPayload(payload *DeleteHostsOKBody) *DeleteHostsOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the delete hosts o k response
func (o *DeleteHostsOK) SetPayload(payload *DeleteHostsOKBody) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *DeleteHostsOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// DeleteHostsBadRequestCode is the HTTP code returned for type DeleteHostsBadRequest
const DeleteHostsBadRequestCode int = 400

/*DeleteHostsBadRequest bad request

swagger:response deleteHostsBadRequest
*/
type DeleteHostsBadRequest struct {

	/*
	  In: Body
	*/
	Payload *DeleteHostsBadRequestBody `json:"body,omitempty"`
}

// NewDeleteHostsBadRequest creates DeleteHostsBadRequest with default headers values
func NewDeleteHostsBadRequest() *DeleteHostsBadRequest {

	return &DeleteHostsBadRequest{}
}

// WithPayload adds the payload to the delete hosts bad request response
func (o *DeleteHostsBadRequest) WithPayload(payload *DeleteHostsBadRequestBody) *DeleteHostsBadRequest {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the delete hosts bad request response
func (o *DeleteHostsBadRequest) SetPayload(payload *DeleteHostsBadRequestBody) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *DeleteHostsBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(400)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// DeleteHostsInternalServerErrorCode is the HTTP code returned for type DeleteHostsInternalServerError
const DeleteHostsInternalServerErrorCode int = 500

/*DeleteHostsInternalServerError Server error

swagger:response deleteHostsInternalServerError
*/
type DeleteHostsInternalServerError struct {
}

// NewDeleteHostsInternalServerError creates DeleteHostsInternalServerError with default headers values
func NewDeleteHostsInternalServerError() *DeleteHostsInternalServerError {

	return &DeleteHostsInternalServerError{}
}

// WriteResponse to the client
func (o *DeleteHostsInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(500)
}
