// Code generated by go-swagger; DO NOT EDIT.

package hosts_api

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// DeleteHostOKCode is the HTTP code returned for type DeleteHostOK
const DeleteHostOKCode int = 200

/*DeleteHostOK successfully delete the host

swagger:response deleteHostOK
*/
type DeleteHostOK struct {

	/*
	  In: Body
	*/
	Payload *DeleteHostOKBody `json:"body,omitempty"`
}

// NewDeleteHostOK creates DeleteHostOK with default headers values
func NewDeleteHostOK() *DeleteHostOK {

	return &DeleteHostOK{}
}

// WithPayload adds the payload to the delete host o k response
func (o *DeleteHostOK) WithPayload(payload *DeleteHostOKBody) *DeleteHostOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the delete host o k response
func (o *DeleteHostOK) SetPayload(payload *DeleteHostOKBody) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *DeleteHostOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// DeleteHostBadRequestCode is the HTTP code returned for type DeleteHostBadRequest
const DeleteHostBadRequestCode int = 400

/*DeleteHostBadRequest bad request

swagger:response deleteHostBadRequest
*/
type DeleteHostBadRequest struct {

	/*
	  In: Body
	*/
	Payload *DeleteHostBadRequestBody `json:"body,omitempty"`
}

// NewDeleteHostBadRequest creates DeleteHostBadRequest with default headers values
func NewDeleteHostBadRequest() *DeleteHostBadRequest {

	return &DeleteHostBadRequest{}
}

// WithPayload adds the payload to the delete host bad request response
func (o *DeleteHostBadRequest) WithPayload(payload *DeleteHostBadRequestBody) *DeleteHostBadRequest {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the delete host bad request response
func (o *DeleteHostBadRequest) SetPayload(payload *DeleteHostBadRequestBody) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *DeleteHostBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(400)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// DeleteHostInternalServerErrorCode is the HTTP code returned for type DeleteHostInternalServerError
const DeleteHostInternalServerErrorCode int = 500

/*DeleteHostInternalServerError Server error

swagger:response deleteHostInternalServerError
*/
type DeleteHostInternalServerError struct {
}

// NewDeleteHostInternalServerError creates DeleteHostInternalServerError with default headers values
func NewDeleteHostInternalServerError() *DeleteHostInternalServerError {

	return &DeleteHostInternalServerError{}
}

// WriteResponse to the client
func (o *DeleteHostInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(500)
}
