// Code generated by go-swagger; DO NOT EDIT.

package hosts_api

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// GetHostsOKCode is the HTTP code returned for type GetHostsOK
const GetHostsOKCode int = 200

/*GetHostsOK returns the list of hosts

swagger:response getHostsOK
*/
type GetHostsOK struct {

	/*
	  In: Body
	*/
	Payload *GetHostsOKBody `json:"body,omitempty"`
}

// NewGetHostsOK creates GetHostsOK with default headers values
func NewGetHostsOK() *GetHostsOK {

	return &GetHostsOK{}
}

// WithPayload adds the payload to the get hosts o k response
func (o *GetHostsOK) WithPayload(payload *GetHostsOKBody) *GetHostsOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get hosts o k response
func (o *GetHostsOK) SetPayload(payload *GetHostsOKBody) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetHostsOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetHostsBadRequestCode is the HTTP code returned for type GetHostsBadRequest
const GetHostsBadRequestCode int = 400

/*GetHostsBadRequest bad request

swagger:response getHostsBadRequest
*/
type GetHostsBadRequest struct {

	/*
	  In: Body
	*/
	Payload *GetHostsBadRequestBody `json:"body,omitempty"`
}

// NewGetHostsBadRequest creates GetHostsBadRequest with default headers values
func NewGetHostsBadRequest() *GetHostsBadRequest {

	return &GetHostsBadRequest{}
}

// WithPayload adds the payload to the get hosts bad request response
func (o *GetHostsBadRequest) WithPayload(payload *GetHostsBadRequestBody) *GetHostsBadRequest {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get hosts bad request response
func (o *GetHostsBadRequest) SetPayload(payload *GetHostsBadRequestBody) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetHostsBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(400)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetHostsUnauthorizedCode is the HTTP code returned for type GetHostsUnauthorized
const GetHostsUnauthorizedCode int = 401

/*GetHostsUnauthorized Unauthorized

swagger:response getHostsUnauthorized
*/
type GetHostsUnauthorized struct {
}

// NewGetHostsUnauthorized creates GetHostsUnauthorized with default headers values
func NewGetHostsUnauthorized() *GetHostsUnauthorized {

	return &GetHostsUnauthorized{}
}

// WriteResponse to the client
func (o *GetHostsUnauthorized) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(401)
}

// GetHostsNotFoundCode is the HTTP code returned for type GetHostsNotFound
const GetHostsNotFoundCode int = 404

/*GetHostsNotFound hosts not found

swagger:response getHostsNotFound
*/
type GetHostsNotFound struct {
}

// NewGetHostsNotFound creates GetHostsNotFound with default headers values
func NewGetHostsNotFound() *GetHostsNotFound {

	return &GetHostsNotFound{}
}

// WriteResponse to the client
func (o *GetHostsNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(404)
}
