// Code generated by go-swagger; DO NOT EDIT.

package restapi

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
)

var (
	// SwaggerJSON embedded version of the swagger document used at generation time
	SwaggerJSON json.RawMessage
	// FlatSwaggerJSON embedded flattened version of the swagger document used at generation time
	FlatSwaggerJSON json.RawMessage
)

func init() {
	SwaggerJSON = json.RawMessage([]byte(`{
  "swagger": "2.0",
  "info": {
    "title": "CloudTides-webserver",
    "version": "0.0.1"
  },
  "basePath": "/api/webserver",
  "paths": {
    "/addHost": {
      "post": {
        "description": "add a local machine to webserver database",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "tags": [
          "hosts_api"
        ],
        "operationId": "addOneHost",
        "parameters": [
          {
            "name": "body",
            "in": "body",
            "schema": {
              "description": "local machine registration form",
              "type": "object",
              "properties": {
                "cluster": {
                  "type": "string"
                },
                "datacenter": {
                  "type": "string"
                },
                "hostname": {
                  "type": "string"
                },
                "ip": {
                  "type": "string"
                },
                "password": {
                  "type": "string"
                },
                "policy": {
                  "type": "integer"
                },
                "port": {
                  "type": "integer",
                  "format": "int64"
                },
                "sshkey": {
                  "type": "string"
                },
                "username": {
                  "type": "string"
                }
              }
            }
          }
        ],
        "responses": {
          "201": {
            "description": "local machine registered successfully",
            "schema": {
              "type": "object",
              "properties": {
                "message": {
                  "type": "string"
                }
              }
            }
          },
          "400": {
            "description": "bad request",
            "schema": {
              "type": "object",
              "properties": {
                "message": {
                  "type": "string"
                }
              }
            }
          },
          "401": {
            "description": "Unauthorized"
          }
        }
      }
    },
    "/deleteHost": {
      "post": {
        "description": "delete a host",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "tags": [
          "hosts_api"
        ],
        "operationId": "deleteHost",
        "parameters": [
          {
            "name": "body",
            "in": "body",
            "schema": {
              "description": "use hostname to delete host",
              "type": "object",
              "properties": {
                "hostname": {
                  "type": "string"
                }
              }
            }
          }
        ],
        "responses": {
          "200": {
            "description": "successfully delete the host",
            "schema": {
              "type": "object",
              "properties": {
                "hostname": {
                  "type": "string"
                }
              }
            }
          },
          "400": {
            "description": "bad request",
            "schema": {
              "type": "object",
              "properties": {
                "message": {
                  "type": "string"
                }
              }
            }
          },
          "500": {
            "description": "Server error"
          }
        }
      }
    },
    "/getHosts": {
      "get": {
        "description": "returns all machines belong to a user",
        "produces": [
          "application/json"
        ],
        "tags": [
          "hosts_api"
        ],
        "operationId": "getHosts",
        "responses": {
          "200": {
            "description": "returns the list of hosts",
            "schema": {
              "type": "object",
              "properties": {
                "message": {
                  "type": "string"
                },
                "results": {
                  "type": "array",
                  "items": {
                    "type": "object",
                    "properties": {
                      "cluster": {
                        "type": "string"
                      },
                      "datacenter": {
                        "type": "string"
                      },
                      "hostname": {
                        "type": "string"
                      },
                      "ip": {
                        "type": "string"
                      },
                      "policy": {
                        "type": "integer"
                      },
                      "port": {
                        "type": "integer",
                        "format": "int64"
                      },
                      "sshkey": {
                        "type": "string"
                      }
                    }
                  }
                }
              }
            }
          },
          "400": {
            "description": "bad request",
            "schema": {
              "type": "object",
              "properties": {
                "message": {
                  "type": "string"
                }
              }
            }
          },
          "401": {
            "description": "Unauthorized"
          },
          "404": {
            "description": "hosts not found"
          }
        }
      }
    },
    "/hostInfo": {
      "get": {
        "description": "return one machines info",
        "produces": [
          "application/json"
        ],
        "tags": [
          "hosts_api"
        ],
        "operationId": "queryOneHostInfo",
        "parameters": [
          {
            "type": "string",
            "name": "hostname",
            "in": "query"
          }
        ],
        "responses": {
          "200": {
            "description": "list the hosts' info",
            "schema": {
              "type": "object",
              "properties": {
                "currentRAM": {
                  "type": "number",
                  "format": "float"
                },
                "hostname": {
                  "type": "string"
                },
                "ip": {
                  "type": "string",
                  "minLength": 1
                },
                "percentCPU": {
                  "type": "number",
                  "format": "float"
                },
                "percentRAM": {
                  "type": "number",
                  "format": "float"
                },
                "port": {
                  "type": "string"
                },
                "totalRAM": {
                  "type": "number",
                  "format": "float"
                }
              }
            }
          },
          "400": {
            "description": "bad request",
            "schema": {
              "type": "object",
              "properties": {
                "message": {
                  "type": "string"
                }
              }
            }
          },
          "401": {
            "description": "Unauthorized"
          }
        }
      }
    },
    "/hostsStatus": {
      "get": {
        "description": "return all machines info",
        "produces": [
          "application/json"
        ],
        "tags": [
          "hosts_api"
        ],
        "operationId": "queryHostInfo",
        "responses": {
          "200": {
            "description": "list the hosts' info",
            "schema": {
              "type": "array",
              "items": {
                "type": "object",
                "properties": {
                  "currentRAM": {
                    "type": "number",
                    "format": "float"
                  },
                  "hostname": {
                    "type": "string"
                  },
                  "ip": {
                    "type": "string",
                    "minLength": 1
                  },
                  "percentCPU": {
                    "type": "number",
                    "format": "float"
                  },
                  "percentRAM": {
                    "type": "number",
                    "format": "float"
                  },
                  "port": {
                    "type": "string"
                  },
                  "totalRAM": {
                    "type": "number",
                    "format": "float"
                  }
                }
              }
            }
          },
          "400": {
            "description": "bad request",
            "schema": {
              "type": "object",
              "properties": {
                "message": {
                  "type": "string"
                }
              }
            }
          },
          "401": {
            "description": "Unauthorized"
          }
        }
      }
    }
  }
}`))
	FlatSwaggerJSON = json.RawMessage([]byte(`{
  "swagger": "2.0",
  "info": {
    "title": "CloudTides-webserver",
    "version": "0.0.1"
  },
  "basePath": "/api/webserver",
  "paths": {
    "/addHost": {
      "post": {
        "description": "add a local machine to webserver database",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "tags": [
          "hosts_api"
        ],
        "operationId": "addOneHost",
        "parameters": [
          {
            "name": "body",
            "in": "body",
            "schema": {
              "description": "local machine registration form",
              "type": "object",
              "properties": {
                "cluster": {
                  "type": "string"
                },
                "datacenter": {
                  "type": "string"
                },
                "hostname": {
                  "type": "string"
                },
                "ip": {
                  "type": "string"
                },
                "password": {
                  "type": "string"
                },
                "policy": {
                  "type": "integer"
                },
                "port": {
                  "type": "integer",
                  "format": "int64"
                },
                "sshkey": {
                  "type": "string"
                },
                "username": {
                  "type": "string"
                }
              }
            }
          }
        ],
        "responses": {
          "201": {
            "description": "local machine registered successfully",
            "schema": {
              "type": "object",
              "properties": {
                "message": {
                  "type": "string"
                }
              }
            }
          },
          "400": {
            "description": "bad request",
            "schema": {
              "type": "object",
              "properties": {
                "message": {
                  "type": "string"
                }
              }
            }
          },
          "401": {
            "description": "Unauthorized"
          }
        }
      }
    },
    "/deleteHost": {
      "post": {
        "description": "delete a host",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "tags": [
          "hosts_api"
        ],
        "operationId": "deleteHost",
        "parameters": [
          {
            "name": "body",
            "in": "body",
            "schema": {
              "description": "use hostname to delete host",
              "type": "object",
              "properties": {
                "hostname": {
                  "type": "string"
                }
              }
            }
          }
        ],
        "responses": {
          "200": {
            "description": "successfully delete the host",
            "schema": {
              "type": "object",
              "properties": {
                "hostname": {
                  "type": "string"
                }
              }
            }
          },
          "400": {
            "description": "bad request",
            "schema": {
              "type": "object",
              "properties": {
                "message": {
                  "type": "string"
                }
              }
            }
          },
          "500": {
            "description": "Server error"
          }
        }
      }
    },
    "/getHosts": {
      "get": {
        "description": "returns all machines belong to a user",
        "produces": [
          "application/json"
        ],
        "tags": [
          "hosts_api"
        ],
        "operationId": "getHosts",
        "responses": {
          "200": {
            "description": "returns the list of hosts",
            "schema": {
              "type": "object",
              "properties": {
                "message": {
                  "type": "string"
                },
                "results": {
                  "type": "array",
                  "items": {
                    "$ref": "#/definitions/ResultsItems0"
                  }
                }
              }
            }
          },
          "400": {
            "description": "bad request",
            "schema": {
              "type": "object",
              "properties": {
                "message": {
                  "type": "string"
                }
              }
            }
          },
          "401": {
            "description": "Unauthorized"
          },
          "404": {
            "description": "hosts not found"
          }
        }
      }
    },
    "/hostInfo": {
      "get": {
        "description": "return one machines info",
        "produces": [
          "application/json"
        ],
        "tags": [
          "hosts_api"
        ],
        "operationId": "queryOneHostInfo",
        "parameters": [
          {
            "type": "string",
            "name": "hostname",
            "in": "query"
          }
        ],
        "responses": {
          "200": {
            "description": "list the hosts' info",
            "schema": {
              "type": "object",
              "properties": {
                "currentRAM": {
                  "type": "number",
                  "format": "float"
                },
                "hostname": {
                  "type": "string"
                },
                "ip": {
                  "type": "string",
                  "minLength": 1
                },
                "percentCPU": {
                  "type": "number",
                  "format": "float"
                },
                "percentRAM": {
                  "type": "number",
                  "format": "float"
                },
                "port": {
                  "type": "string"
                },
                "totalRAM": {
                  "type": "number",
                  "format": "float"
                }
              }
            }
          },
          "400": {
            "description": "bad request",
            "schema": {
              "type": "object",
              "properties": {
                "message": {
                  "type": "string"
                }
              }
            }
          },
          "401": {
            "description": "Unauthorized"
          }
        }
      }
    },
    "/hostsStatus": {
      "get": {
        "description": "return all machines info",
        "produces": [
          "application/json"
        ],
        "tags": [
          "hosts_api"
        ],
        "operationId": "queryHostInfo",
        "responses": {
          "200": {
            "description": "list the hosts' info",
            "schema": {
              "type": "array",
              "items": {
                "$ref": "#/definitions/QueryHostInfoOKBodyItems0"
              }
            }
          },
          "400": {
            "description": "bad request",
            "schema": {
              "type": "object",
              "properties": {
                "message": {
                  "type": "string"
                }
              }
            }
          },
          "401": {
            "description": "Unauthorized"
          }
        }
      }
    }
  },
  "definitions": {
    "QueryHostInfoOKBodyItems0": {
      "type": "object",
      "properties": {
        "currentRAM": {
          "type": "number",
          "format": "float"
        },
        "hostname": {
          "type": "string"
        },
        "ip": {
          "type": "string",
          "minLength": 1
        },
        "percentCPU": {
          "type": "number",
          "format": "float"
        },
        "percentRAM": {
          "type": "number",
          "format": "float"
        },
        "port": {
          "type": "string"
        },
        "totalRAM": {
          "type": "number",
          "format": "float"
        }
      }
    },
    "ResultsItems0": {
      "type": "object",
      "properties": {
        "cluster": {
          "type": "string"
        },
        "datacenter": {
          "type": "string"
        },
        "hostname": {
          "type": "string"
        },
        "ip": {
          "type": "string"
        },
        "policy": {
          "type": "integer"
        },
        "port": {
          "type": "integer",
          "format": "int64"
        },
        "sshkey": {
          "type": "string"
        }
      }
    }
  }
}`))
}
