// Code generated by go-swagger; DO NOT EDIT.

package hosts

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"context"
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime/middleware"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// AddOneHostHandlerFunc turns a function with the right signature into a add one host handler
type AddOneHostHandlerFunc func(AddOneHostParams) middleware.Responder

// Handle executing the request and returning a response
func (fn AddOneHostHandlerFunc) Handle(params AddOneHostParams) middleware.Responder {
	return fn(params)
}

// AddOneHostHandler interface for that can handle valid add one host params
type AddOneHostHandler interface {
	Handle(AddOneHostParams) middleware.Responder
}

// NewAddOneHost creates a new http.Handler for the add one host operation
func NewAddOneHost(ctx *middleware.Context, handler AddOneHostHandler) *AddOneHost {
	return &AddOneHost{Context: ctx, Handler: handler}
}

/* AddOneHost swagger:route POST /addHost hosts addOneHost

AddOneHost add one host API

*/
type AddOneHost struct {
	Context *middleware.Context
	Handler AddOneHostHandler
}

func (o *AddOneHost) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewAddOneHostParams()
	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}

// AddOneHostBody add one host body
//
// swagger:model AddOneHostBody
type AddOneHostBody struct {

	// completed
	Completed bool `json:"completed,omitempty"`

	// id
	// Read Only: true
	ID int64 `json:"id,omitempty"`

	// ip
	// Min Length: 1
	IP string `json:"ip,omitempty"`
}

// Validate validates this add one host body
func (o *AddOneHostBody) Validate(formats strfmt.Registry) error {
	var res []error

	if err := o.validateIP(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *AddOneHostBody) validateIP(formats strfmt.Registry) error {
	if swag.IsZero(o.IP) { // not required
		return nil
	}

	if err := validate.MinLength("body"+"."+"ip", "body", o.IP, 1); err != nil {
		return err
	}

	return nil
}

// ContextValidate validate this add one host body based on the context it is used
func (o *AddOneHostBody) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := o.contextValidateID(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *AddOneHostBody) contextValidateID(ctx context.Context, formats strfmt.Registry) error {

	if err := validate.ReadOnly(ctx, "body"+"."+"id", "body", int64(o.ID)); err != nil {
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (o *AddOneHostBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *AddOneHostBody) UnmarshalBinary(b []byte) error {
	var res AddOneHostBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}

// AddOneHostCreatedBody add one host created body
//
// swagger:model AddOneHostCreatedBody
type AddOneHostCreatedBody struct {

	// completed
	Completed bool `json:"completed,omitempty"`

	// id
	// Read Only: true
	ID int64 `json:"id,omitempty"`

	// ip
	// Min Length: 1
	IP string `json:"ip,omitempty"`
}

// Validate validates this add one host created body
func (o *AddOneHostCreatedBody) Validate(formats strfmt.Registry) error {
	var res []error

	if err := o.validateIP(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *AddOneHostCreatedBody) validateIP(formats strfmt.Registry) error {
	if swag.IsZero(o.IP) { // not required
		return nil
	}

	if err := validate.MinLength("addOneHostCreated"+"."+"ip", "body", o.IP, 1); err != nil {
		return err
	}

	return nil
}

// ContextValidate validate this add one host created body based on the context it is used
func (o *AddOneHostCreatedBody) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := o.contextValidateID(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *AddOneHostCreatedBody) contextValidateID(ctx context.Context, formats strfmt.Registry) error {

	if err := validate.ReadOnly(ctx, "addOneHostCreated"+"."+"id", "body", int64(o.ID)); err != nil {
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (o *AddOneHostCreatedBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *AddOneHostCreatedBody) UnmarshalBinary(b []byte) error {
	var res AddOneHostCreatedBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}
