// Code generated by go-swagger; DO NOT EDIT.

package hosts

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"lhj-broker/pkg/models"
)

// AddOneHostCreatedCode is the HTTP code returned for type AddOneHostCreated
const AddOneHostCreatedCode int = 201

/*AddOneHostCreated Created

swagger:response addOneHostCreated
*/
type AddOneHostCreated struct {

	/*
	  In: Body
	*/
	Payload *AddOneHostCreatedBody `json:"body,omitempty"`
}

// NewAddOneHostCreated creates AddOneHostCreated with default headers values
func NewAddOneHostCreated() *AddOneHostCreated {

	return &AddOneHostCreated{}
}

// WithPayload adds the payload to the add one host created response
func (o *AddOneHostCreated) WithPayload(payload *AddOneHostCreatedBody) *AddOneHostCreated {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the add one host created response
func (o *AddOneHostCreated) SetPayload(payload *AddOneHostCreatedBody) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *AddOneHostCreated) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(201)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

/*AddOneHostDefault error

swagger:response addOneHostDefault
*/
type AddOneHostDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewAddOneHostDefault creates AddOneHostDefault with default headers values
func NewAddOneHostDefault(code int) *AddOneHostDefault {
	if code <= 0 {
		code = 500
	}

	return &AddOneHostDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the add one host default response
func (o *AddOneHostDefault) WithStatusCode(code int) *AddOneHostDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the add one host default response
func (o *AddOneHostDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the add one host default response
func (o *AddOneHostDefault) WithPayload(payload *models.Error) *AddOneHostDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the add one host default response
func (o *AddOneHostDefault) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *AddOneHostDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
