// Code generated by go-swagger; DO NOT EDIT.

package hosts

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"context"
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime/middleware"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// FindHostsHandlerFunc turns a function with the right signature into a find hosts handler
type FindHostsHandlerFunc func(FindHostsParams) middleware.Responder

// Handle executing the request and returning a response
func (fn FindHostsHandlerFunc) Handle(params FindHostsParams) middleware.Responder {
	return fn(params)
}

// FindHostsHandler interface for that can handle valid find hosts params
type FindHostsHandler interface {
	Handle(FindHostsParams) middleware.Responder
}

// NewFindHosts creates a new http.Handler for the find hosts operation
func NewFindHosts(ctx *middleware.Context, handler FindHostsHandler) *FindHosts {
	return &FindHosts{Context: ctx, Handler: handler}
}

/* FindHosts swagger:route GET /addHost hosts findHosts

FindHosts find hosts API

*/
type FindHosts struct {
	Context *middleware.Context
	Handler FindHostsHandler
}

func (o *FindHosts) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewFindHostsParams()
	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}

// FindHostsOKBodyItems0 find hosts o k body items0
//
// swagger:model FindHostsOKBodyItems0
type FindHostsOKBodyItems0 struct {

	// completed
	Completed bool `json:"completed,omitempty"`

	// id
	// Read Only: true
	ID int64 `json:"id,omitempty"`

	// ip
	// Min Length: 1
	IP string `json:"ip,omitempty"`
}

// Validate validates this find hosts o k body items0
func (o *FindHostsOKBodyItems0) Validate(formats strfmt.Registry) error {
	var res []error

	if err := o.validateIP(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *FindHostsOKBodyItems0) validateIP(formats strfmt.Registry) error {
	if swag.IsZero(o.IP) { // not required
		return nil
	}

	if err := validate.MinLength("ip", "body", o.IP, 1); err != nil {
		return err
	}

	return nil
}

// ContextValidate validate this find hosts o k body items0 based on the context it is used
func (o *FindHostsOKBodyItems0) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := o.contextValidateID(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *FindHostsOKBodyItems0) contextValidateID(ctx context.Context, formats strfmt.Registry) error {

	if err := validate.ReadOnly(ctx, "id", "body", int64(o.ID)); err != nil {
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (o *FindHostsOKBodyItems0) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *FindHostsOKBodyItems0) UnmarshalBinary(b []byte) error {
	var res FindHostsOKBodyItems0
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}
