name: backend-CD

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: self-hosted
    steps:

      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

      - name: Publish to Registry
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          name: wuwentao1998/cloudtides_backend
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          workdir: tides-server
          tags: "latest"

      - name: Transfer yml file to Aliyun
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.REMOTE_HOST }}
          username: ${{ secrets.REMOTE_USER }}
          password: ${{ secrets.SSH_PASSWORD }}
          port: 22
          source: "tides-server/cloudtides_backend.yml"
          target: "/home/runner"

      - name: Upgrade the platform using SSH
        uses: fifsky/ssh-action@master
        with:
          command: |
            cd /home/runner/tides-server
            kubectl delete -f cloudtides_backend.yml
            kubectl apply -f cloudtides_backend.yml
          host: ${{ secrets.REMOTE_HOST }}
          user: ${{ secrets.REMOTE_USER }}
          pass: ${{ secrets.SSH_PASSWORD }}
